packages:
  - packages/*
  - apps/*
  - examples/*
catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.8.3
  vite: ^6.0.7
  '@vitejs/plugin-react': ^4.3.4
  wrangler: ^3.53.0
  tailwindcss: ^4.1.5
  '@tailwindcss/vite': ^4.1.5
  tw-animate-css: ^1.2.8
  '@tanstack/react-query': ^5.74.3
  '@tanstack/react-query-devtools': ^5.74.3
  '@tanstack/query-sync-storage-persister': ^5.74.3
  '@tanstack/react-query-persist-client': ^5.74.3
  wagmi: ^2.15.0
  '@wagmi/core': ^2.17.0
  viem: ^2.29.2
  ox: ^0.6.12
  cva: npm:class-variance-authority@^0.7.1
  sonner: ^2.0.3
  globals: ^16.0.0
  '@types/node': ^22.14.1
  porto: ^0.0.23
  '@types/react': ^19
  '@types/react-dom': ^19
  vite-plugin-mkcert: ^1.17.8
  '@biomejs/biome': ^1.9.4
ignoredBuiltDependencies:
  - better-sqlite3
overrides:
  porto: 0.0.23
