packages:
  - "packages/*"
  - "apps/*"

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.8.3
  vite: ^6.0.7
  '@vitejs/plugin-react': ^4.3.4
  wrangler: ^3.53.0
  tailwindcss: ^4.1.5
  '@tailwindcss/vite': ^4.1.5
  tw-animate-css: ^1.2.8

  # State & networking
  "@tanstack/react-query": ^5.74.3
  "@tanstack/react-query-devtools": ^5.74.3
  "@tanstack/query-sync-storage-persister": ^5.74.3
  "@tanstack/react-query-persist-client": ^5.74.3
  "@tanstack/react-router": ^1.120.5
  "@tanstack/react-router-devtools": ^1.120.5
  "@tanstack/router-plugin": ^1.120.5
  "@types/node": "^22.14.1"
  "@types/react": "^19"
  "@types/react-dom": "^19"

  # Web3
  wagmi: ^2.15.0
  '@wagmi/core': ^2.17.0
  viem: ^2.29.2
  ox: ^0.6.12
  porto: ^0.0.23

  # UI
  lucide-react: ^0.511.0
  sonner: ^2.0.3

  # Utilities
  cva: npm:class-variance-authority@^0.7.1
  zustand: ^5.0.4
  idb-keyval: ^6.2.2
  globals: ^16.0.0
  vite-plugin-mkcert: ^1.17.8
  "@biomejs/biome": ^1.9.4
  "@ariakit/react": ^0.4.17
  "@ariakit/tailwind": "^0.1.5"

ignoredBuiltDependencies:
  - better-sqlite3

overrides:
  porto: 0.0.23
