#!/usr/bin/env tsx
// @ts-nocheck
/*
 * Generates a fresh secp256k1 private key for the delegated escrow signer
 * and writes it to `apps/vite-react/.env.local`.
 *
 * This file is meant for LOCAL DEVELOPMENT ONLY.
 * Never commit the resulting `.env.local` file.
 */

import { existsSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

function generateKey() {
  const privateKey = generatePrivateKey()
  const { address } = privateKeyToAccount(privateKey)
  return { privateKey, address }
}

function writeEnv(privateKey: string, envPath: string) {
  const banner = '# Auto-generated by scripts/gen-escrow-key.ts – DO NOT COMMIT\n'
  const content = `${banner}VITE_ESCROW_SIGNER_PRIVATE_KEY=${privateKey}\n`
  writeFileSync(envPath, content, { encoding: 'utf8', flag: 'w' })
}

function main() {
  const { privateKey, address } = generateKey()
  const envPath = join(__dirname, '../apps/vite-react/.env.local')

  // Don't accidentally overwrite an existing key without notice.
  if (existsSync(envPath)) {
    console.error(`\u26A0\uFE0F  ${envPath} already exists. Remove it first if you really want to regenerate the key.`)
    process.exit(1)
  }

  writeEnv(privateKey, envPath)

  console.log('\nEscrow signer generated successfully!')
  console.log('  Address      :', address)
  console.log('  Private key  :', privateKey)
  console.log('\nThe key has been written to:', envPath)
  console.log('Remember: this file is in .gitignore and should never be committed.')
}

main() 